---
apiVersion: rabbitmq.com/v1beta2
kind: Vhost
metadata:
  name: source-vhost
spec:
  name: source
  rabbitmqClusterReference:
    name: example-rabbit
---
apiVersion: rabbitmq.com/v1beta2
kind: Vhost
metadata:
  name: destination-vhost
spec:
  name: destination
  rabbitmqClusterReference:
    name: example-rabbit
